# Generated by Django 4.2 on 2023-12-24 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
