# Generated by Django 4.2 on 2023-12-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('paper_answer', models.TextField()),
                ('difficulty_ratio', models.CharField(max_length=100)),
                ('chapter_ratio', models.CharField(max_length=100)),
            ],
        ),
    ]
